### ISSUE TITLE
Salinity of a salt lake

### ISSUE THREAD

**Issue by aymenmootamri** [satish1901/In-situ-Water-quality-monitoring-in-Oil-and-Gas-operations#3]
Greetings @satish1901 

I'm using this repository to determine the salinity of a salt lake, but I'm facing trouble differentiating between turbidity and salinity based on the output provided by the code. Also The repository includes four different equations: w_qual_1, w_qual_2, w_qual_3, and w_qual_4. Can you recommend the best equation to use for my case ?

notice: I've discovered that the equation in the paper is different that the one used in code. Am I wrong?

**Comment by satish1901** [comment]
Hello 
Sorry for the late response 
The correct output is: w_qual_1
Please use that!
I will fix those in the code!

The paper contains the normalized form of these equations, for visualizations, it renders similar results with very less computation.

I hope this helps, Please let me know if there is any other confusion 

Thank you
